/**
 * Analytics Configuration
 * Defines FREE/MIDDLE/PREMIUM metrics and pricing for each business category
 */

export const ANALYTICS_TIERS = {
  restaurant: {
    name: 'Restaurant',
    pricing: { free: 0, middle: 15000, premium: 45000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'reviewCountThisMonth',
      'topComplaint',
      'ratingDistribution',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'reviewCountThisMonth',
      'topComplaint',
      'ratingDistribution',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'seasonalTrends',
      'staffQualityScore',
      'pricePerceptionScore',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'reviewCountThisMonth',
      'topComplaint',
      'ratingDistribution',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'seasonalTrends',
      'staffQualityScore',
      'pricePerceptionScore',
      'aiRecommendations',
      'menuOptimizationInsights',
      'competitiveThreeatAnalysis',
      'customerPersonaBreakdown',
      'revenueImpactForecast',
      'monthlyExecReport',
    ],
  },
  bank: {
    name: 'Bank',
    pricing: { free: 0, middle: 25000, premium: 75000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'trustScore',
      'topComplaint',
      'ratingDistribution',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'trustScore',
      'topComplaint',
      'ratingDistribution',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'serviceQualityScore',
      'feeComplaintFrequency',
      'safetyTrustScore',
      'customerSegmentSatisfaction',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'trustScore',
      'topComplaint',
      'ratingDistribution',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'serviceQualityScore',
      'feeComplaintFrequency',
      'safetyTrustScore',
      'customerSegmentSatisfaction',
      'regulatoryRiskFlagging',
      'customerRetentionForecast',
      'churnPredictor',
      'competitiveWinLossAnalysis',
      'complianceGapReport',
      'executiveDashboard',
      'quarterlyBusinessReview',
    ],
  },
  healthcare: {
    name: 'Healthcare',
    pricing: { free: 0, middle: 20000, premium: 60000 },
    free: [
      'avgRating',
      'totalReviews',
      'patientSatisfactionScore',
      'topComplaint',
      'ratingDistribution',
      'responseRate',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'patientSatisfactionScore',
      'topComplaint',
      'ratingDistribution',
      'responseRate',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'doctorStaffRating',
      'serviceQualityPerDepartment',
      'patientSafetyConcer nDetection',
      'treatmentOutcomeSentiment',
      'accessibilityFeedback',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'patientSatisfactionScore',
      'topComplaint',
      'ratingDistribution',
      'responseRate',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'doctorStaffRating',
      'serviceQualityPerDepartment',
      'patientSafetyConcer nDetection',
      'treatmentOutcomeSentiment',
      'accessibilityFeedback',
      'patientSatisfactionNPS',
      'riskFlaggging',
      'patientRetentionForecast',
      'doctorPerformanceComparison',
      'treatmentRecommendationAnalysis',
      'referralPatternDetection',
      'medicalEthicsComplianceCheck',
      'healthcareBoardReports',
      'realTimeAlertSystem',
    ],
  },
  hotel: {
    name: 'Hotel & Hospitality',
    pricing: { free: 0, middle: 18000, premium: 55000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'roomQualityScore',
      'staffServiceScore',
      'cleanlinessScore',
      'priceValuePerception',
      'competitorRank',
      'seasonalDemandForecast',
      'amenitySatisfaction',
      'geographicGuestSource',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'roomQualityScore',
      'staffServiceScore',
      'cleanlinessScore',
      'priceValuePerception',
      'competitorRank',
      'seasonalDemandForecast',
      'amenitySatisfaction',
      'geographicGuestSource',
      'revenueOptimizationSuggestions',
      'bookingConversionForecast',
      'guestPersonaAnalysis',
      'roomTypePerformance',
      'staffTrainingRecommendations',
      'competitorRateAnalysis',
      'reputationRiskAlerts',
      'otaIntegrationReports',
      'dynamicPricingSuggestions',
    ],
  },
  healthcare_clinic: {
    name: 'Clinic',
    pricing: { free: 0, middle: 20000, premium: 60000 },
    free: [
      'avgRating',
      'totalReviews',
      'patientSatisfactionScore',
      'topComplaint',
      'ratingDistribution',
      'responseRate',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'patientSatisfactionScore',
      'topComplaint',
      'ratingDistribution',
      'responseRate',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'waitTimeScore',
      'serviceQualityByType',
      'safetyMentions',
      'treatmentFeedback',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'patientSatisfactionScore',
      'topComplaint',
      'ratingDistribution',
      'responseRate',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'waitTimeScore',
      'serviceQualityByType',
      'safetyMentions',
      'treatmentFeedback',
      'npsScore',
      'riskAlerts',
      'retentionForecast',
      'staffPerformance',
      'referralAnalysis',
      'complianceCheck',
    ],
  },
  pharmacy: {
    name: 'Pharmacy',
    pricing: { free: 0, middle: 14000, premium: 42000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'staffKnowledgeScore',
      'priceCompetitivenessScore',
      'productAvailabilitySentiment',
      'customerServiceScore',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'staffKnowledgeScore',
      'priceCompetitivenessScore',
      'productAvailabilitySentiment',
      'customerServiceScore',
      'aiRecommendations',
      'inventoryOptimization',
      'stockingInsights',
      'customerPersonas',
      'retentionStrategy',
      'competitiveAnalysis',
      'loyaltyEffectiveness',
    ],
  },
  telecom: {
    name: 'Telecommunications',
    pricing: { free: 0, middle: 22000, premium: 65000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'serviceReliabilityScore',
      'supportResponsivenessScore',
      'competitorRank',
      'technicalIssueFrequency',
      'priceValuePerception',
      'customerSatisfactionSegments',
      'churnRiskIndicators',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'serviceReliabilityScore',
      'supportResponsivenessScore',
      'competitorRank',
      'technicalIssueFrequency',
      'priceValuePerception',
      'customerSatisfactionSegments',
      'churnRiskIndicators',
      'networkPerformanceInsights',
      'slaComplianceForecasting',
      'customerSegmentation',
      'supportPerformanceMetrics',
      'competitiveThreeatAssessment',
      'retentionStrategy',
      'executiveDashboard',
      'apiOptimization',
      'realTimeNetworkAlerts',
    ],
  },
  supermarket: {
    name: 'Supermarket',
    pricing: { free: 0, middle: 12000, premium: 40000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'productAvailabilitySentiment',
      'pricePerceptionScore',
      'competitorRank',
      'staffCourtesyScore',
      'stockFeedback',
      'seasonalProductTrends',
      'locationInsights',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'productAvailabilitySentiment',
      'pricePerceptionScore',
      'competitorRank',
      'staffCourtesyScore',
      'stockFeedback',
      'seasonalProductTrends',
      'locationInsights',
      'inventoryOptimizationInsights',
      'productMixRecommendations',
      'customerDemographic',
      'competitiveAnalysis',
      'pricingStrategy',
      'trafficForecast',
      'loyaltyEffectiveness',
      'staffPerformanceAnalytics',
    ],
  },
  education: {
    name: 'Education',
    pricing: { free: 0, middle: 16000, premium: 50000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'teachingQualityScore',
      'facilityScore',
      'competitorRank',
      'studentSatisfactionScore',
      'parentFeedbackSentiment',
      'curriculumFeedback',
      'studentAchievementMentions',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'teachingQualityScore',
      'facilityScore',
      'competitorRank',
      'studentSatisfactionScore',
      'parentFeedbackSentiment',
      'curriculumFeedback',
      'studentAchievementMentions',
      'enrollmentForecast',
      'studentRetentionInsights',
      'competitivePositioning',
      'staffPerformanceAnalysis',
      'programEffectiveness',
      'parentEngagementMetrics',
      'accreditationRiskAssessment',
    ],
  },
  real_estate: {
    name: 'Real Estate',
    pricing: { free: 0, middle: 18000, premium: 55000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'propertyQualityScore',
      'agentResponsivenessScore',
      'competitorRank',
      'transactionFeedback',
      'locationDesirabilityScore',
      'pricePerceptionScore',
      'processExperienceFeedback',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'propertyQualityScore',
      'agentResponsivenessScore',
      'competitorRank',
      'transactionFeedback',
      'locationDesirabilityScore',
      'pricePerceptionScore',
      'processExperienceFeedback',
      'marketingEffectiveness',
      'leadConversionInsights',
      'agentPerformanceRanking',
      'propertyTypePerformance',
      'marketTrendAnalysis',
      'seasonalDemandForecast',
      'competitiveMarketAnalysis',
    ],
  },
  electronics: {
    name: 'Electronics & Tech',
    pricing: { free: 0, middle: 17000, premium: 52000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'productQualityScore',
      'priceCompetitivenessScore',
      'competitorRank',
      'customerServiceScore',
      'productAvailabilitySentiment',
      'warrantyFeedback',
      'afterSalesServiceScore',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'productQualityScore',
      'priceCompetitivenessScore',
      'competitorRank',
      'customerServiceScore',
      'productAvailabilitySentiment',
      'warrantyFeedback',
      'afterSalesServiceScore',
      'productPerformanceAnalysis',
      'inventoryOptimizationInsights',
      'customerPersonaAnalysis',
      'competitivePricingStrategy',
      'supplierPerformanceTracking',
      'seasonalTrendForecast',
      'loyaltyProgramEffectiveness',
    ],
  },
  fitness: {
    name: 'Fitness & Nutrition',
    pricing: { free: 0, middle: 13000, premium: 42000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'trainerQualityScore',
      'facilityQualityScore',
      'competitorRank',
      'memberSatisfactionScore',
      'equipmentFeedback',
      'classQualityFeedback',
      'resultsAchievementMentions',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'trainerQualityScore',
      'facilityQualityScore',
      'competitorRank',
      'memberSatisfactionScore',
      'equipmentFeedback',
      'classQualityFeedback',
      'resultsAchievementMentions',
      'retentionForecast',
      'churnRiskInsights',
      'classPopularityAnalysis',
      'memberSegmentation',
      'marketingEffectiveness',
      'competitivePositioning',
      'memberEngagementMetrics',
    ],
  },
  travel: {
    name: 'Travel & Insurance',
    pricing: { free: 0, middle: 19000, premium: 58000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'serviceFulfillmentScore',
      'priceValuePerception',
      'competitorRank',
      'claimProcessFeedback',
      'customerSupportResponsivenessScore',
      'destinationSatisfaction',
      'packageValueFeedback',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'serviceFulfillmentScore',
      'priceValuePerception',
      'competitorRank',
      'claimProcessFeedback',
      'customerSupportResponsivenessScore',
      'destinationSatisfaction',
      'packageValueFeedback',
      'riskAssessment',
      'claimFraudIndicators',
      'retentionForecast',
      'packagePopularityAnalysis',
      'seasonalDemandForecast',
      'competitiveMarketAnalysis',
      'customerSegmentationAnalysis',
    ],
  },
  other: {
    name: 'Other',
    pricing: { free: 0, middle: 15000, premium: 45000 },
    free: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
    ],
    middle: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'customerSatisfactionScore',
      'serviceQualityScore',
      'pricePerceptionScore',
      'reviewVelocity',
    ],
    premium: [
      'avgRating',
      'totalReviews',
      'responseRate',
      'topComplaint',
      'ratingDistribution',
      'reviewCountThisMonth',
      'sentimentScore',
      'topPraisedThemes',
      'topComplaintThemes',
      'competitorRank',
      'customerSatisfactionScore',
      'serviceQualityScore',
      'pricePerceptionScore',
      'reviewVelocity',
      'aiRecommendations',
      'competitiveAnalysis',
      'customerPersonas',
      'retentionForecast',
      'growthOpportunities',
      'monthlyReport',
    ],
  },
};

/**
 * Get enabled metrics for a category and subscription tier
 * @param {string} category - Category key (e.g., 'restaurant', 'bank')
 * @param {string} tier - Subscription tier ('free', 'middle', 'premium')
 * @returns {array} Array of enabled metric keys
 */
export function getEnabledMetrics(category, tier = 'free') {
  const categoryConfig = ANALYTICS_TIERS[category];
  if (!categoryConfig) return ANALYTICS_TIERS.other[tier] || [];
  return categoryConfig[tier] || categoryConfig.free || [];
}

/**
 * Get category name
 * @param {string} category - Category key
 * @returns {string} Display name
 */
export function getCategoryName(category) {
  return ANALYTICS_TIERS[category]?.name || ANALYTICS_TIERS.other.name;
}

/**
 * Get pricing for a category
 * @param {string} category - Category key
 * @returns {object} { free, middle, premium } pricing in RWF
 */
export function getCategoryTierPricing(category) {
  return ANALYTICS_TIERS[category]?.pricing || ANALYTICS_TIERS.other.pricing;
}

/**
 * Get all categories
 * @returns {array} Array of { key, name } objects
 */
export function getAllCategories() {
  return Object.keys(ANALYTICS_TIERS).map(key => ({
    key,
    name: ANALYTICS_TIERS[key].name,
  }));
}

/**
 * Validate category exists
 * @param {string} category - Category key
 * @returns {boolean}
 */
export function isValidCategory(category) {
  return !!ANALYTICS_TIERS[category];
}

/**
 * Get next tier suggestions
 * @param {string} category - Category key
 * @param {string} currentTier - Current tier ('free', 'middle', 'premium')
 * @returns {object} { tier, features, price }
 */
export function getUpgradeSuggestion(category, currentTier = 'free') {
  if (currentTier === 'premium') return null;

  const nextTier = currentTier === 'free' ? 'middle' : 'premium';
  const categoryConfig = ANALYTICS_TIERS[category];
  if (!categoryConfig) return null;

  return {
    tier: nextTier,
    price: categoryConfig.pricing[nextTier],
    newFeatures: categoryConfig[nextTier].filter(
      metric => !categoryConfig[currentTier].includes(metric)
    ),
  };
}
